version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mssql
      - DB_USER=sa
      - DB_PASSWORD=QuynhChi123
      - DB_NAME=TITKET
    depends_on:
      - mssql

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=QuynhChi123
      - MSSQL_PID=Developer
